In [2]:
import tensorflow as tf
from transformers import TFGPT2LMHeadModel, GPT2Tokenizer

In [3]:
from transformers import GPT2Tokenizer, TFGPT2LMHeadModel, TextDataset, DataCollatorForLanguageModeling, Trainer, TrainingArguments

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = TFGPT2LMHeadModel.from_pretrained("gpt2", pad_token_id=tokenizer.eos_token_id)
tokenizer.pad_token = tokenizer.eos_token

All PyTorch model weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [5]:
def responder(pregunta):
    input = tokenizer.encode(pregunta,return_tensors="tf")
    modelg = model.generate(input,max_length=50,num_beams = 5, no_repeat_ngram_size=2, early_stopping=True)
    outputD= tokenizer.decode(modelg[0], skip_special_tokens=True, clean_up_tokenization_spaces=True)
    return outputD

In [8]:
responder("Where is United Estates")

'Where is United Estates located?\n\nUnited Estations is located in the heart of New York City. It is one of the oldest and most well-known residential and commercial real estate developments on the East Coast. The building was built in 1892 and is now the largest residential building in North America.\n\n\nWhat is the difference between the building and the other buildings on this site? What are the differences between these two buildings? Are there any differences in how they are constructed? How does'

In [9]:
responder("Are Machine intelligent than human being")

'Are Machine intelligent than human being?\n\nThe answer to this question is a resounding "yes". The problem is that machine intelligence is not the same as human intelligence. Machine intelligence does not know what is going on in the world, but it does know that it is doing something. It knows what it wants to do, and it will do it. This is what makes it so powerful. If you want to make a machine intelligent, you have to be able to understand what you are doing'

In [ ]:
import torch

class IMDbDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = IMDbDataset(train_encodings, train_labels)


In [1]:
data = ["Dónde está Berlín? <SEP> Se encuentra en Sucre, Bolivia, a 3 cuadras de la plaza principal",
"¿Cuál es la ubicación de Berlín? <SEP> Berlín se ubica en Sucre, Bolivia, a unas tres cuadras de la plaza principal",
"En qué lugar está Berlín? <SEP> Está en el centro de Sucre, Bolivia, a una corta distancia de la plaza principal",
"¿Dónde se halla Berlín? <SEP> Se halla en Sucre, Bolivia, a 3 cuadras de la plaza principal.",
"¿Dónde se localiza Berlín? <SEP> Se localiza en Sucre, Bolivia, a unas pocas cuadras de la plaza principal.",
"Dónde se encuentra Berlín <SEP> Se encuentra en Sucre, Bolivia, a tres cuadras de la plaza principal",
"¿En qué parte de Sucre está Berlín? <SEP> Berlín está en el corazón de Sucre, Bolivia, a corta distancia de la plaza principal."
]

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

class ChatbotDataset(Dataset):
    def __init__(self, datos, tokenizer, max_length=128):
        self.data = []
        self.tokenizer = tokenizer
        self.max_length = max_length
        for i in datos:
            question, answer = i.split('[SEP]')
            self.data.append((question,answer))
    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        question, answer = self.data[index]
        # Tokenizar y codificar las secuencias
        input_ids = self.tokenizer.encode(question, add_special_tokens=True, max_length=self.max_length, truncation=True)
        target_ids = self.tokenizer.encode(answer, add_special_tokens=True, max_length=self.max_length, truncation=True)

        # Convertir a tensores de PyTorch
        input_ids = torch.tensor(input_ids, dtype=torch.long)
        target_ids = torch.tensor(target_ids, dtype=torch.long)

        return {"input_ids": input_ids, "target_ids": target_ids}

# Ejemplo de uso:
# Supongamos que tienes un modelo tokenizador llamado 'tokenizer' y un archivo de datos llamado 'chatbot_data.txt'
tokenizer = YourTokenizer()  # Reemplaza YourTokenizer con el objeto real de tu tokenizador
dataset = ChatbotDataset(data_path='chatbot_data.txt', tokenizer=tokenizer)

# Divide el conjunto de datos en entrenamiento y validación (80-20 por ejemplo)
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size])

# Crea los dataloaders
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=32, shuffle=False)


In [8]:
vector = "abc <sep> kjd"
vector.strip().split('<sep>')

['abc ', ' kjd']

In [9]:
tokenized_data = tokenizer(data, return_tensors="pt", padding=True, truncation=True)
tokenized_data

{'input_ids': tensor([[   35, 10205,   358,    68,  1556,  6557,  4312,    75, 39588,    30,
          1001,  2207,    84,   298,   430,   551, 47352,   260,    11, 38496,
            11,   257,   513, 18912,   324,  8847,   390,  8591, 42433, 10033,
         50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256,
         50256, 50256, 50256],
        [  126,   123, 46141,  6557,    75,  1658,  8591, 20967,   291, 32009,
         18840,   390,  4312,    75, 39588,    30,  4312,    75, 39588,   384,
         20967,  3970,   551, 47352,   260,    11, 38496,    11,   257,   555,
           292,   256,   411, 18912,   324,  8847,   390,  8591, 42433, 10033,
         50256, 50256, 50256],
        [ 4834,   627,  2634,   300, 35652,  1556,  6557,  4312,    75, 39588,
            30, 10062,  6557,   551,  1288,  1247,   305,   390, 47352,   260,
            11, 38496,    11,   257,   555,    64, 12794,    64,  1233,  1192,
           544,   390,  8591, 42433, 10033, 50256, 5025

In [29]:
from torch.utils.data import Dataset, DataLoader
class MyTextDataset(Dataset):
    def __init__(self, tokenized_data):
        self.input_ids = tokenized_data["input_ids"]
        self.attention_mask = tokenized_data["attention_mask"]
        self.label = tokenized_data["input_ids"]

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            "input_ids": self.input_ids[idx],
            "attention_mask": self.attention_mask[idx],
            "label":self.input_ids[idx]
        }



In [ ]:
from transformers import GPT2LMHeadModel, GPT2Config, GPT2Tokenizer, TextDataset, DataCollatorForLanguageModeling, Trainer, TrainingArguments
embed_dim = 2560
num_heads = 12

# Ajustar embed_dim para que sea divisible uniformemente por num_heads
if embed_dim % num_heads != 0:
    embed_dim = (embed_dim // num_heads) * num_heads

# Configurar el modelo con los nuevos valores
config = GPT2Config(embed_dim=embed_dim, num_heads=num_heads)
# Cargar el modelo preentrenado y el tokenizador
model_name = "EleutherAI/gpt-neo-2.7B"
modelPytorch = GPT2LMHeadModel.from_pretrained(model_name, config=config)
tokenizerPytorch = GPT2Tokenizer.from_pretrained(model_name)
tokenizerPytorch.pad_token = tokenizerPytorch.eos_token

In [49]:

tokenized_dataPytorch = tokenizerPytorch(data, return_tensors="pt", padding=True, truncation=True)

In [50]:
text_dataset = MyTextDataset(tokenized_dataPytorch)

In [51]:
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizerPytorch, mlm=False)
train_dataloader = DataLoader(text_dataset, collate_fn=data_collator, batch_size=2, shuffle=True)


In [52]:
for batch in train_dataloader:
    inputs = batch["input_ids"]
    #labels = batch["labels"]
    outputs = modelPytorch(inputs, labels=inputs)
    loss = outputs.loss
    loss.backward()

In [53]:
import torch
def responder(pregunta):
    input = tokenizerPytorch.encode(pregunta,return_tensors="pt")
    attention_mask = torch.ones_like(input)
    if attention_mask.any():
        modelPy = modelPytorch.generate(input, attention_mask= attention_mask,max_length=50,num_beams = 5, no_repeat_ngram_size=2, early_stopping=True, pad_token_id=tokenizerPytorch.eos_token_id)
        outputD= tokenizerPytorch.decode(modelPy[0], skip_special_tokens=True, clean_up_tokenization_spaces=True)
        return outputD
    return "Mascara vacia"

In [54]:
responder("En qué lugar está Berlín?")

"En qué lugar está Berlín?\n\nNo, I don't think so. I mean, you know, it's not like we're going to be able to do anything about it. It's just that we have to"

In [10]:
text_dataset = TextDataset(
    tokenizer=tokenizer,
    file_path=None,  # Puedes proporcionar un archivo si tus datos están almacenados en un archivo en lugar de una lista en memoria.
    block_size=128,  # Tamaño del bloque para la generación de texto
    overwrite_cache=False,  # Si debes sobrescribir la caché existente
    **tokenized_data
)

TypeError: TextDataset.__init__() got an unexpected keyword argument 'input_ids'

In [ ]:
toke

In [67]:
input = tokenizer(data)
input.input_ids[0]

[35,
 10205,
 358,
 68,
 1556,
 6557,
 4312,
 75,
 39588,
 30,
 1001,
 2207,
 84,
 298,
 430,
 551,
 47352,
 260,
 11,
 38496,
 11,
 257,
 513,
 18912,
 324,
 8847,
 390,
 8591,
 42433,
 10033]

In [68]:
tokenizer.encode(data[0])

[35,
 10205,
 358,
 68,
 1556,
 6557,
 4312,
 75,
 39588,
 30,
 1001,
 2207,
 84,
 298,
 430,
 551,
 47352,
 260,
 11,
 38496,
 11,
 257,
 513,
 18912,
 324,
 8847,
 390,
 8591,
 42433,
 10033]

In [38]:

# Tokenizar los datos
tokenized_data = tokenizer(data, truncation=True, padding=True)

# Crear un conjunto de datos
train_dataset = TextDataset(
    tokenizer=tokenizer,
    file_path="dummy_file.txt",  # Utilizamos un nombre de archivo ficticio
    text_column="text",  # Nombre de la columna que contiene los textos
    data_frame=tokenized_data,
    data_files={"train": ["dummy_file.txt"]},  # Esto es necesario para evitar el error
)

# Preparar el DataCollator
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)

# Definir

TypeError: TextDataset.__init__() got an unexpected keyword argument 'text_column'

In [20]:
training_args = TrainingArguments(
    output_dir="./gpt2-fine-tuned",
    overwrite_output_dir=True,
    num_train_epochs=1,
    per_device_train_batch_size=16,
    save_steps=10_000,
    save_total_limit=2,
)
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataloader,
)

trainer.train()

# Guardar el modelo fine-tuned
trainer.save_model()


AttributeError: 'TFGPT2LMHeadModel' object has no attribute 'to'

In [1]:
from transformers import BertForQuestionAnswering, BertTokenizer
import torch

# Cargar el modelo preentrenado y el tokenizador
model = BertForQuestionAnswering.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Ejemplo de entrada: pregunta y contexto
question = "What is the capital of France?"
context = "Paris is the capital of France."

# Tokenizar la entrada
inputs = tokenizer(question, context, return_tensors='pt')

# Pasar la entrada a través del modelo
outputs = model(**inputs)

# Obtener los logits asociados con cada token en la secuencia tokenizada
start_logits = outputs.start_logits
end_logits = outputs.end_logits

print("Dimensionalidad de la entrada:", inputs['input_ids'].shape)
print("Dimensionalidad de los logits de inicio:", start_logits.shape)
print("Dimensionalidad de los logits de fin:", end_logits.shape)


Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['qa_outputs.weight', 'qa_outputs.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Dimensionalidad de la entrada: torch.Size([1, 17])
Dimensionalidad de los logits de inicio: torch.Size([1, 17])
Dimensionalidad de los logits de fin: torch.Size([1, 17])


In [3]:
outputs[0]

tensor([[-0.1115, -0.2291,  0.2048,  0.5086, -0.1032,  0.3235,  0.2025, -0.1516,
          0.1464, -0.1851,  0.2534,  0.5938, -0.0069,  0.2593,  0.2905,  0.2370,
          0.2380]], grad_fn=<CloneBackward0>)

In [4]:
outputs[1]

tensor([[-0.1782,  0.2064, -0.0011, -0.2340, -0.3734, -0.0957, -0.4119,  0.1857,
         -0.1770, -0.4938, -0.0999, -0.1218, -0.3205,  0.0053, -0.2130, -0.1041,
         -0.0948]], grad_fn=<CloneBackward0>)

In [5]:
inputs

{'input_ids': tensor([[ 101, 2054, 2003, 1996, 3007, 1997, 2605, 1029,  102, 3000, 2003, 1996,
         3007, 1997, 2605, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [9]:
#end_position = torch.argmax(end_logits).item()
outputs.start_logits

tensor([[-0.1115, -0.2291,  0.2048,  0.5086, -0.1032,  0.3235,  0.2025, -0.1516,
          0.1464, -0.1851,  0.2534,  0.5938, -0.0069,  0.2593,  0.2905,  0.2370,
          0.2380]], grad_fn=<CloneBackward0>)

In [38]:
outputs.end_logits

tensor([[-0.1782,  0.2064, -0.0011, -0.2340, -0.3734, -0.0957, -0.4119,  0.1857,
         -0.1770, -0.4938, -0.0999, -0.1218, -0.3205,  0.0053, -0.2130, -0.1041,
         -0.0948]], grad_fn=<CloneBackward0>)

In [39]:
torch.argmax(outputs.start_logits).item()

11

In [23]:
outputs_slice = outputs.end_logits[0,11:]
outputs_slice

tensor([-0.1218, -0.3205,  0.0053, -0.2130, -0.1041, -0.0948],
       grad_fn=<SliceBackward0>)

In [24]:
torch.argmax(outputs_slice)

tensor(2)

In [37]:
inputs['input_ids'][0][:]

tensor([ 101, 2054, 2003, 1996, 3007, 1997, 2605, 1029,  102, 3000, 2003, 1996,
        3007, 1997, 2605, 1012,  102])

In [32]:
# Seleccionar la posición de inicio con el valor más alto
start_position = torch.argmax(outputs.start_logits).item()

# Seleccionar la posición de fin después de la posición de inicio
end_logits_slice = outputs.end_logits[0,start_position:]
end_position = torch.argmax(end_logits_slice).item() + start_position

# Des-Tokenización para obtener la respuesta final
answer = tokenizer.decode(inputs['input_ids'][0, start_position:end_position + 1].tolist())

print("Respuesta Final:", answer)


Respuesta Final: the capital of


In [ ]:
answer = tokenizer.decode(inputs['input_ids'][0, start_position:end_position+1].tolist(), skip_special_tokens=True)

print("Respuesta Final:", answer)

In [21]:
end_position.item()

15

In [22]:
end_position

tensor(15)

In [29]:
inputs

{'input_ids': tensor([[ 101, 2054, 2003, 1996, 3007, 1997, 2605, 1029,  102, 3000, 2003, 1996,
         3007, 1997, 2605, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}