In [18]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchviz import make_dot  # Necesitarás instalar la librería torchviz

# Definir el modelo simple
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(1, 2)
        self.fc2 = nn.Linear(2, 3)

    def forward(self, x):
        print('1')
        print(x)
        x = self.fc1(x)
        print('2')
        print(x)
        x = self.fc2(x)
        print('3')
        print(x)
        return x

# Crear una instancia del modelo
model = SimpleModel()

# Definir función de pérdida y optimizador
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Datos de entrada y etiquetas
x = torch.randn((1, 1), requires_grad=True)  # entrada con un solo dato
y_true = torch.randn((1, 1), requires_grad=False)  # etiqueta aleatoria

# Pase hacia adelante y cálculo de la pérdida
y_pred = model(x)
loss = criterion(y_pred, y_true)

# Visualizar el grafo computacional
make_dot(loss, params=dict(model.named_parameters()))


1
tensor([[-0.1265]], requires_grad=True)
2
tensor([[-0.5952, -0.1582]], grad_fn=<AddmmBackward0>)
3
tensor([[-0.1979,  0.0381, -1.0062]], grad_fn=<AddmmBackward0>)


ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

In [19]:
loss

tensor(0.2213, grad_fn=<MseLossBackward0>)

In [22]:
for i in model.named_parameters():
    print(i)

('fc1.weight', Parameter containing:
tensor([[-0.1868],
        [-0.8978]], requires_grad=True))
('fc1.bias', Parameter containing:
tensor([-0.6188, -0.2718], requires_grad=True))
('fc2.weight', Parameter containing:
tensor([[ 0.1323,  0.3506],
        [-0.7030,  0.0150],
        [ 0.4481,  0.5974]], requires_grad=True))
('fc2.bias', Parameter containing:
tensor([-0.0637, -0.3779, -0.6450], requires_grad=True))


In [21]:
-0.1868 * -0.1265

0.0236302

In [23]:
0.0236302 - 0.6188

-0.5951698